# NB_10_Purview_Lineage_Annotations
# Layer: Governance
# Purpose: Apply Delta table properties that support cataloguing and lineage review.

from datetime import datetime, timezone

from src.config_loader import load_config, lakehouse_table

config = load_config()

TABLE_CATALOGUE = [
    {
        "table": lakehouse_table(config, "bronze", "bronze_training_enrolments"),
        "description": "Raw training enrolment data ingested from controlled Excel landing folders.",
        "source": "Files/landing/training/training_enrolments_*.xlsx",
        "owner": "data-engineering@example.org",
        "sensitivity": "Confidential_Internal",
        "layer": "Bronze",
        "pii": "false",
        "retention_years": "7",
    },
    {
        "table": lakehouse_table(config, "bronze", "file_ingestion_registry"),
        "description": "Registry of every file ingested. MD5 hash enables duplicate detection and audit reconciliation.",
        "source": "Generated by NB_02_Bronze_Excel_Ingest",
        "owner": "data-engineering@example.org",
        "sensitivity": "Confidential_Internal",
        "layer": "Bronze",
        "pii": "false",
        "retention_years": "7",
    },
    {
        "table": lakehouse_table(config, "bronze", "api_call_log"),
        "description": "REST API call audit log for SLA monitoring and failure diagnosis.",
        "source": "Generated by NB_03_Bronze_REST_API_Ingest",
        "owner": "data-engineering@example.org",
        "sensitivity": "Confidential_Internal",
        "layer": "Bronze",
        "pii": "false",
        "retention_years": "2",
    },
    {
        "table": lakehouse_table(config, "bronze", "schema_change_log"),
        "description": "Excel schema drift log for new and removed source columns.",
        "source": "Generated by NB_02_Bronze_Excel_Ingest",
        "owner": "data-engineering@example.org",
        "sensitivity": "Confidential_Internal",
        "layer": "Bronze",
        "pii": "false",
        "retention_years": "3",
    },
    {
        "table": lakehouse_table(config, "silver", "silver_training_enrolments"),
        "description": "Cleansed and deduplicated training enrolments.",
        "source": lakehouse_table(config, "bronze", "bronze_training_enrolments"),
        "owner": "data-engineering@example.org",
        "sensitivity": "Confidential_Internal",
        "layer": "Silver",
        "pii": "false",
        "retention_years": "5",
    },
    {
        "table": lakehouse_table(config, "gold", "fact_training_completion"),
        "description": "Gold fact table for training completion analytics.",
        "source": lakehouse_table(config, "silver", "silver_training_enrolments"),
        "owner": "analytics@example.org",
        "sensitivity": "Confidential_Internal",
        "layer": "Gold",
        "pii": "false",
        "retention_years": "3",
    },
]

for entry in TABLE_CATALOGUE:
    stamp = str(datetime.now(timezone.utc))
    props = {
        "description": entry["description"],
        "lineage.source": entry["source"],
        "lineage.layer": entry["layer"],
        "owner": entry["owner"],
        "sensitivity_label": entry["sensitivity"],
        "gdpr.contains_pii": entry["pii"],
        "data_retention_years": entry["retention_years"],
        "last_annotated": stamp,
    }
    prop_sql = ", ".join([f"'{key}' = '{value}'" for key, value in props.items()])
    try:
        spark.sql(f"ALTER TABLE {entry['table']} SET TBLPROPERTIES ({prop_sql})")
        print(f"Annotated {entry['table']}")
    except Exception as exc:
        print(f"Could not annotate {entry['table']}: {exc}")
